/**
 * 기능 카탈로그 레지스트리 — **이 파일이 SoT 다.**
 *
 * ────────────────────────────────────────────────────────────────────
 *  규약
 * ────────────────────────────────────────────────────────────────────
 *
 * 1. `defaultPolicy` 는 **현재 배포된 실제 동작**이다. 지금 잠겨 있지 않은
 *    기능은 전부 `{ minTier: 'anon', gateMode: 'open' }` 이어야 한다.
 *    이 규칙 덕분에 이 시스템을 배포해도 사용자 화면이 바뀌지 않는다.
 *    기능을 새로 잠글 때는 게이트 코드와 이 기본값을 같은 커밋에 넣는다.
 *
 *    지금 `open` 이 아닌 항목은 **딱 세 부류뿐이고 전부 이미 배포된 가드다**:
 *      - `admin.*`            → `app/admin/layout.tsx` 의 `requireAdmin('/admin')`
 *      - `me.*` (/me 라우트)   → 각 페이지의 `requireUser(...)`
 *      - `news.*` 4건          → `components/news/locked-section.tsx` 비로그인 잠금
 *    이 목록은 `__tests__/unit/permissions-registry.test.ts` 의
 *    `PRE_GATED` 상수가 그대로 강제한다 — 여기에 없는 기능이 잠겨 있으면
 *    테스트가 깨지므로, 실수로 사용자 화면을 바꾸는 커밋이 통과하지 못한다.
 *
 * 1-b. `wired` 는 **그 기본값을 읽어 화면을 바꾸는 코드가 실제로 있는가**를
 *    가리킨다. 정책 저장은 언제나 즉시 반영되지만, `FeatureGate` 마운트와
 *    (`masking: 'server'` 인 경우) API 마스킹은 기능마다 따로 넣어야 하므로
 *    두 사실이 갈라진다. 갈라진 채로 콘솔이 스위치를 보여주면 운영자는
 *    "잠갔다" 고 믿고 실제로는 열려 있는 상태가 된다 — 그래서 배선 여부를
 *    레지스트리가 들고 콘솔이 배지로 드러낸다. 배선 커밋에서 `wired: true`
 *    를 게이트 코드와 **같은 커밋**에 넣는다. 현재 배선된 기능은 0건이다.
 *
 * 2. `recommendedMinTier` / `recommendedGateMode` 는 카탈로그 조사가 제안한
 *    값이며 **런타임 판정에 일절 관여하지 않는다.** 어드민 화면이 "제안"
 *    컬럼으로 보여주고, 운영자가 받아들이면 DB 오버라이드가 된다.
 *
 * 3. `featureId` 는 한 번 배포되면 바꾸지 않는다. 이름이 나빠졌으면 새 키를
 *    만들고 옛 키에 `retired: true` 를 단다 — 감사 로그가 옛 키를 참조한다.
 *
 * 4. 형식: `<namespace>.<feature>[-<qualifier>]`, `.` 은 정확히 하나.
 *    정규식은 `FEATURE_ID_PATTERN`. 네임스페이스는 URL 이 아니라 **제품면**
 *    기준이다 — `/rankings` 와 `/[industryId]/rankings` 는 둘 다 `rankings.*`.
 *
 * 5. `supportedGateModes: ['open']` 은 **잠금 봉인**이다. 카탈로그 §5
 *    "게이팅하면 안 되는 것"(SEO 착지면·법적 문서·로그인/수신거부·문의 창구·
 *    신뢰 문서)에 해당하는 기능은 어드민 셀렉트에서 `open` 외 선택지가
 *    아예 없다. 문서로만 적어 둔 금지 목록은 언젠가 반드시 어겨지므로,
 *    타입과 어드민 UI 가 강제하게 만든 것이 이 필드의 목적이다.
 *    반대로 `admin.*` 은 `['hidden']` 으로 고정한다 — 이미 `requireAdmin` 이
 *    지키고 있고 신규 시스템이 손대면 회귀 위험만 생긴다(카탈로그 §N).
 *
 * 전수 카탈로그 근거: `_workspace/01_plan/permission-catalog.md`
 * (페이지 50 라우트 + 비라우트 제품면 2 = 52, 기능 160)
 */

import type { FeatureDef, GateMode, PageDef } from './types'

/** featureId 형식 검증. 유닛 테스트가 전 항목에 대해 강제한다. */
export const FEATURE_ID_PATTERN =
  /^[a-z][a-z0-9]*(-[a-z0-9]+)*\.[a-z][a-z0-9]*(-[a-z0-9]+)*$/

// ────────────────────────────────────────────────────────────────────
//  게이트 방식 프리셋 — 어드민 셀렉트의 선택지를 결정한다.
// ────────────────────────────────────────────────────────────────────

/** 잠금 봉인. 카탈로그 §5 "게이팅하면 안 되는 것". */
const SEALED_OPEN: readonly GateMode[] = ['open']

/** `requireAdmin` 이 이미 지키는 영역. 운영자가 바꿀 수 있는 게 없다. */
const ADMIN_FIXED: readonly GateMode[] = ['hidden']

/** 값이 없는 UI 컨트롤 — 노출 아니면 제거 둘 뿐. */
const CONTROL_MODES: readonly GateMode[] = ['open', 'hidden']

/** 기간·범위 셀렉트 — 선택지 일부만 여는 partial 이 성립한다. */
const PERIOD_MODES: readonly GateMode[] = ['open', 'partial', 'hidden']

/**
 * 리스트·표, 그리고 "일부만 실값" 이 성립하는 블록(지표 묶음·차원 분해).
 * 상위 N개(`visibleRows`) 또는 상위 K개 가리기(`blurTopK`) 둘 다 쓸 수 있다.
 */
const LIST_MODES: readonly GateMode[] = ['open', 'partial', 'teaser', 'blur', 'hidden']

/** 쪼갤 단위가 없는 단일 블록(차트·카드) — 통째로 열거나 가린다. */
const BLOCK_MODES: readonly GateMode[] = ['open', 'blur', 'teaser', 'hidden']

/** 페이지 목록 — 어드민 좌측 리스트의 원천. */
export const PAGES: readonly PageDef[] = [
  // ─── 데이터 화면 ───
  { id: 'home', label: '홈', route: '/', order: 1 },
  { id: 'rankings', label: '섹터킹 픽(점수 랭킹)', route: '/rankings', order: 2 },
  { id: 'stock', label: '종목 상세', route: '/stock/[ticker]', order: 3 },
  { id: 'industry', label: '산업 대시보드', route: '/[industryId]', order: 4 },
  {
    id: 'industry-money-flow',
    label: '섹터 자금 흐름',
    route: '/[industryId]/money-flow',
    order: 5,
  },
  {
    id: 'industry-price-changes',
    label: '등락율',
    route: '/[industryId]/price-changes',
    order: 6,
  },
  {
    // 기능은 `/rankings` 와 100% 공유한다(같은 `RankingsPage`). 카탈로그 §F 의
    // "featureId 는 공유하고 pageId 만 둘로 둔다" 결정에 따라 이 페이지에만
    // 소속된 기능은 없다 — 라우트 인벤토리를 잃지 않기 위해 항목은 남긴다.
    id: 'industry-rankings',
    label: '산업별 점수 랭킹',
    route: '/[industryId]/rankings',
    order: 7,
  },
  {
    id: 'industry-statistics',
    label: '통계',
    route: '/[industryId]/statistics',
    order: 8,
  },
  { id: 'market-size', label: '시장 규모', route: '/market-size', order: 9 },
  { id: 'sectors', label: '섹터 허브', route: '/sectors', order: 10 },
  { id: 'sector-detail', label: '섹터 상세', route: '/sectors/[sectorId]', order: 11 },
  { id: 'analysts', label: '애널리스트 성적표', route: '/analysts', order: 12 },
  { id: 'analyst-detail', label: '애널리스트 상세', route: '/analysts/[id]', order: 13 },
  { id: 'indices', label: '세계 지수', route: '/indices', order: 14 },
  {
    // 라우트가 없는 독립 제품면 — 홈에만 마운트된다(카탈로그 §A-1, §6.2).
    id: 'calendar',
    label: '경제 캘린더',
    route: '/',
    order: 15,
  },

  // ─── 콘텐츠 ───
  { id: 'news', label: '마켓 리포트 목록', route: '/news', order: 16 },
  { id: 'news-detail', label: '마켓 리포트 본문', route: '/news/[id]', order: 17 },

  // ─── 전역 셸 ───
  {
    // 페이지가 아니라 모든 라우트에 얹히는 셸(카탈로그 §1.1).
    id: 'shell',
    label: '전역 셸(상단바)',
    route: '*',
    order: 18,
  },

  // ─── 개인 ───
  { id: 'me-home', label: '내 페이지 홈', route: '/me', order: 19 },
  { id: 'me-watchlist', label: '워치리스트', route: '/me/watchlist', order: 20 },
  { id: 'me-notes', label: '내 메모', route: '/me/notes', order: 21 },
  { id: 'me-settings', label: '내 설정', route: '/me/settings', order: 22 },
  { id: 'me-onboarding', label: '온보딩', route: '/me/onboarding', order: 23 },

  // ─── 인증·문서·법적 ───
  { id: 'login', label: '로그인', route: '/login', order: 24 },
  { id: 'guide', label: '이용 안내 허브', route: '/guide', order: 25 },
  {
    id: 'guide-money-flow',
    label: '가이드: 자금 흐름 읽는 법',
    route: '/guide/how-to-read-money-flow',
    order: 26,
  },
  {
    id: 'guide-mcap-vs-netbuy',
    label: '가이드: 시총 변화 vs 순매수',
    route: '/guide/market-cap-change-vs-net-buying',
    order: 27,
  },
  {
    id: 'guide-sector-rotation',
    label: '가이드: 섹터 로테이션',
    route: '/guide/sector-rotation',
    order: 28,
  },
  { id: 'methodology', label: '방법론', route: '/methodology', order: 29 },
  { id: 'data-sources', label: '데이터 출처', route: '/data-sources', order: 30 },
  { id: 'editorial-policy', label: '편집 정책', route: '/editorial-policy', order: 31 },
  { id: 'about', label: '서비스 소개', route: '/about', order: 32 },
  { id: 'contact', label: '문의·제보', route: '/contact', order: 33 },
  { id: 'terms', label: '이용약관', route: '/terms', order: 34 },
  { id: 'privacy', label: '개인정보 처리방침', route: '/privacy', order: 35 },
  {
    id: 'email-unsubscribed',
    label: '구독 해지 완료',
    route: '/email/unsubscribed',
    order: 36,
  },
  { id: 'design-system', label: '디자인 시스템(내부)', route: '/design-system', order: 37 },

  // ─── 관리자 ───
  { id: 'admin-home', label: '관리자 대시보드', route: '/admin', order: 38, adminOnly: true },
  { id: 'admin-news', label: '리포트 목록', route: '/admin/news', order: 39, adminOnly: true },
  {
    id: 'admin-news-new',
    label: '리포트 작성',
    route: '/admin/news/new',
    order: 40,
    adminOnly: true,
  },
  {
    id: 'admin-news-edit',
    label: '리포트 수정',
    route: '/admin/news/[id]/edit',
    order: 41,
    adminOnly: true,
  },
  {
    id: 'admin-news-preview-email',
    label: '발송 메일 미리보기',
    route: '/admin/news/[id]/preview-email',
    order: 42,
    adminOnly: true,
  },
  {
    id: 'admin-econ-calendar',
    label: '경제 캘린더 관리',
    route: '/admin/economic-calendar',
    order: 43,
    adminOnly: true,
  },
  {
    id: 'admin-econ-calendar-new',
    label: '캘린더 이벤트 등록',
    route: '/admin/economic-calendar/new',
    order: 44,
    adminOnly: true,
  },
  {
    id: 'admin-econ-calendar-edit',
    label: '캘린더 이벤트 수정',
    route: '/admin/economic-calendar/[id]/edit',
    order: 45,
    adminOnly: true,
  },
  {
    id: 'admin-contributors',
    label: '기여자 관리',
    route: '/admin/contributors',
    order: 46,
    adminOnly: true,
  },
  {
    id: 'admin-contributors-new',
    label: '기여자 등록',
    route: '/admin/contributors/new',
    order: 47,
    adminOnly: true,
  },
  {
    id: 'admin-contributors-edit',
    label: '기여자 수정',
    route: '/admin/contributors/[id]/edit',
    order: 48,
    adminOnly: true,
  },
  { id: 'admin-contact', label: '문의 관리', route: '/admin/contact', order: 49, adminOnly: true },
  {
    id: 'admin-contact-detail',
    label: '문의 상세',
    route: '/admin/contact/[id]',
    order: 50,
    adminOnly: true,
  },
  { id: 'admin-users', label: '사용자 관리', route: '/admin/users', order: 51, adminOnly: true },
  {
    id: 'admin-email-log',
    label: '이메일 발송 로그',
    route: '/admin/email-log',
    order: 52,
    adminOnly: true,
  },
]

/** 기능 카탈로그. 키가 featureId 다. */
export const FEATURES: Record<string, FeatureDef> = {
  // ══════════════════════════════════════════════════════════════════
  //  A. 홈 `/` — 16
  // ══════════════════════════════════════════════════════════════════

  'home.hero': {
    label: '히어로 슬로건',
    pageId: 'home',
    description: '"시장의 돈이 어디로 흐르는가" 제호 + 뉴스 메일 CTA',
    location: 'components/industry-dashboard.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'home.region-filter': {
    label: '지역 필터',
    pageId: 'home',
    description: '전체/국내/해외 토글',
    location: 'components/region-toggle.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'home.currency-toggle': {
    label: '통화 토글',
    pageId: 'home',
    description: '₩/$ 표시 전환',
    location: 'components/currency-toggle.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'home.ticker-tape': {
    label: '시세 띠',
    pageId: 'home',
    description: '당일 등락 상위 20종목이 흐르는 띠 (현재 limit=20)',
    location: 'components/dashboard/ticker-tape.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'display',
  },
  'home.onboarding-hint': {
    label: '온보딩 힌트',
    pageId: 'home',
    description: '처음 방문자 안내 스트립',
    location: 'components/onboarding/onboarding-hint-strip.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'home.money-flow-card': {
    label: '산업별 자금 흐름',
    pageId: 'home',
    description: '리드 카드. 기간 토글(1/3/7/14/30일) + 산업별 유입·유출',
    location: 'components/dashboard/industry-money-flow-card.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'home.quick-nav': {
    label: '모바일 바로가기',
    pageId: 'home',
    description: '애널리스트/뉴스/픽/지수/가이드 바로가기 카드',
    location: 'components/dashboard/quick-nav-cards.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'home.news-card': {
    label: '오늘의 마켓 리포트',
    pageId: 'home',
    description: '최신 리포트 요약 카드',
    location: 'components/news/news-home-card-slot.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'teaser',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
  },
  'home.korean-picks': {
    label: '오늘 추천하는 한국 종목',
    pageId: 'home',
    description: '최신 리포트의 KR 추천 종목. 뉴스 본문에서 이미 로그인 게이트 대상인 값',
    location: 'components/dashboard/korean-picks-card.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'home.analyst-scorecard': {
    label: '애널리스트 성적표 카드',
    pageId: 'home',
    description: '"예측대로 맞혔나?" 상위 요약',
    location: 'components/dashboard/analyst-scorecard-card.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'teaser',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'home.sector-king-pick': {
    label: '섹터킹 픽 TOP 5',
    pageId: 'home',
    description: '종합 점수 상위 5종목 표 (useRankings limit:5)',
    location: 'components/dashboard/sector-king-pick-card.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'home.market-pulse': {
    label: '시장 동향 요약 KPI',
    pageId: 'home',
    description: '추적 종목 시총·전일 대비·가장 큰 자금 이동',
    location: 'components/dashboard/market-pulse-strip.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
  },
  'home.market-cap-detail': {
    label: '시총 일자별 드릴다운',
    pageId: 'home',
    description: 'KPI 클릭 시 일자별 차트 + 표 모달',
    location: 'components/dashboard/market-cap-detail-modal.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'hidden',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'home.company-stats': {
    label: '회사 등장 통계 Top 10',
    pageId: 'home',
    description: '섹터 등장 횟수 상위 기업 (현재 10개)',
    location: 'components/dashboard/company-stats-card.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'home.price-changes-card': {
    label: '가격 변화율 카드',
    pageId: 'home',
    description: '기간 토글 + 상승/하락 상위',
    location: 'components/dashboard/price-changes-card.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'home.industry-cards': {
    label: '산업 패권 지도 카드',
    pageId: 'home',
    description: '산업 9개 카드(시총·14일 추세·인사이트 1줄). 홈 SEO fallback 표의 원천이기도 하다',
    location: 'components/industry-dashboard.tsx + components/dashboard/industry-cap-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: LIST_MODES,
    masking: 'display',
    seoIndexed: true,
  },

  // ══════════════════════════════════════════════════════════════════
  //  A-1. 경제 캘린더 (홈에만 마운트되는 독립 제품면) — 7
  // ══════════════════════════════════════════════════════════════════

  'calendar.indicator': {
    label: '경제지표 일정',
    pageId: 'calendar',
    description: '미국·한국 지표 발표 (FRED 자동 + 수동 시드)',
    location: 'components/calendar/category-meta.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: LIST_MODES,
    masking: 'display',
  },
  'calendar.earnings': {
    label: '실적발표 일정',
    pageId: 'calendar',
    description: '추적 602종목 실적 발표일. 원거리 일정이 유료 가치',
    location: 'lib/earnings-calendar.ts + components/calendar/category-meta.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'calendar.ipo': {
    label: '공모주 일정',
    pageId: 'calendar',
    description: '국내 IPO 청약·상장 일정',
    location: 'lib/ipo-calendar.ts + components/calendar/category-meta.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'calendar.month-view': {
    label: '월 그리드 뷰',
    pageId: 'calendar',
    description: '월 42칸 그리드',
    location: 'components/calendar/calendar-month-grid.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'calendar.week-view': {
    label: '주 리스트 뷰',
    pageId: 'calendar',
    description: '주별 리스트',
    location: 'components/calendar/calendar-week-list.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'calendar.event-detail': {
    label: '이벤트 상세',
    pageId: 'calendar',
    description: 'pill 클릭 시 상세 모달',
    location: 'components/calendar/event-pill.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
  },
  'calendar.country-filter': {
    label: '국가 필터',
    pageId: 'calendar',
    description: '전체/국내/미국',
    location: 'components/calendar/calendar-filters.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },

  // ══════════════════════════════════════════════════════════════════
  //  B. 산업 대시보드 `/[industryId]` — 5
  // ══════════════════════════════════════════════════════════════════

  'industry.hegemony-map': {
    label: '패권 지도',
    pageId: 'industry',
    description: '카테고리 탭/그리드 안에 섹터별 종목 뱃지. SEO fallback 섹터 표의 원천',
    location: 'components/hegemony-map.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: LIST_MODES,
    masking: 'display',
    seoIndexed: true,
  },
  'industry.date-selector': {
    label: '과거 날짜 조회',
    pageId: 'industry',
    description: '과거 스냅샷 날짜로 지도 재구성. 과거 시계열이 곧 유료 가치',
    location: 'components/date-selector.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'hidden',
    supportedGateModes: CONTROL_MODES,
    masking: 'server',
  },
  'industry.company-statistics': {
    label: '회사 등장 통계 사이드',
    pageId: 'industry',
    description: '산업 내 다중 섹터 등장 기업 (현재 slice(0,10))',
    location: 'components/company-statistics.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'industry.price-change-card': {
    label: '등락 카드 사이드',
    pageId: 'industry',
    description: '산업 내 등락 상위 (현재 slice(0,10))',
    location: 'components/price-change-card.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'industry.region-filter': {
    label: '지역 필터',
    pageId: 'industry',
    description: '전체/국내/해외 (컨텍스트 바 rightActions)',
    location: 'components/layout/industry-context-bar.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },

  // ══════════════════════════════════════════════════════════════════
  //  C. 섹터 자금 흐름 `/[industryId]/money-flow` — 6
  // ══════════════════════════════════════════════════════════════════

  'money-flow.inflow-cards': {
    label: '자금 유입 섹터',
    pageId: 'industry-money-flow',
    description: '유입 상위 6개 카드 (현재 slice(0,6)). SEO fallback 표의 원천',
    location: 'components/money-flow/money-flow-page-content.tsx + components/money-flow/flow-card.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
    seoIndexed: true,
  },
  'money-flow.outflow-cards': {
    label: '자금 유출 섹터',
    pageId: 'industry-money-flow',
    description: '유출 상위 6개 카드 (현재 slice(0,6))',
    location: 'components/money-flow/money-flow-page-content.tsx + components/money-flow/flow-card.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'money-flow.summary': {
    label: '총유입·총유출·순유입',
    pageId: 'industry-money-flow',
    description: '기간 합계 3지표',
    location: 'components/money-flow/flow-summary.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
  },
  'money-flow.period-toggle': {
    label: '기간 선택',
    pageId: 'industry-money-flow',
    description: '1/3/7/14/30일 (기본 14일)',
    location: 'components/money-flow/money-flow-page-content.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: PERIOD_MODES,
    masking: 'server',
  },
  'money-flow.sector-companies': {
    label: '섹터 내 종목 모달',
    pageId: 'industry-money-flow',
    description: '카드 클릭 시 종목별 시총·등락',
    location: 'components/money-flow/sector-company-list.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'money-flow.sector-trend': {
    label: '섹터 시총 추이',
    pageId: 'industry-money-flow',
    description: '섹터별 기간 추이 차트 + 정렬·전체보기 토글',
    location: 'components/sector-trend/sector-trend-section.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },

  // ══════════════════════════════════════════════════════════════════
  //  D. 등락율 `/[industryId]/price-changes` — 5
  // ══════════════════════════════════════════════════════════════════

  'price-changes.top20-chart': {
    label: '상위 20개 변화율 차트',
    pageId: 'industry-price-changes',
    description: '막대 차트',
    location: 'components/price-changes/price-change-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
  },
  'price-changes.top20-trend': {
    label: '상위 20개 등락율 추이',
    pageId: 'industry-price-changes',
    description: '다중 시리즈 라인 차트',
    location: 'components/statistics/company-trend-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'price-changes.full-table': {
    label: '전체 기업 목록 표',
    pageId: 'industry-price-changes',
    description: '산업 전 종목 등락 표',
    location: 'components/price-changes/price-change-table.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'price-changes.sort-controls': {
    label: '정렬 컨트롤',
    pageId: 'industry-price-changes',
    description: '등락율/시총 등 정렬',
    location: 'components/price-changes/price-changes-page-content.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'price-changes.company-modal': {
    label: '종목 상세 모달',
    pageId: 'industry-price-changes',
    description:
      '행 클릭 시 CompanyDetail. 내부 블록은 stock.* 규칙을 그대로 상속한다(모달 우회 방지 — 카탈로그 §E 주석)',
    location: 'components/company-detail.tsx → components/stock/stock-detail-sections.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'server',
  },

  // ══════════════════════════════════════════════════════════════════
  //  E. 통계 `/[industryId]/statistics` — 7
  // ══════════════════════════════════════════════════════════════════

  'statistics.sector-trend-chart': {
    label: '섹터별 시가총액 추이',
    pageId: 'industry-statistics',
    description: '다중 섹터 라인 차트',
    location: 'components/statistics/sector-trend-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
  },
  'statistics.category-comparison': {
    label: '카테고리별 시가총액',
    pageId: 'industry-statistics',
    description: '비교 막대 차트',
    location: 'components/statistics/category-comparison-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
  },
  'statistics.top-sectors-growth': {
    label: '섹터 성장률 Top/Bottom 5',
    pageId: 'industry-statistics',
    description: '상·하위 5개 섹터 성장률',
    location: 'components/statistics/top-sectors-growth-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'statistics.company-trend-chart': {
    label: '주요 기업 시가총액 추이',
    pageId: 'industry-statistics',
    description: '기업 다중 라인 차트',
    location: 'components/statistics/company-trend-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'statistics.company-ranking': {
    label: '전체 회사 등장 랭킹',
    pageId: 'industry-statistics',
    description: '페이지네이션 표',
    location: 'components/statistics/company-ranking-table.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'statistics.period-filter': {
    label: '기간 필터',
    pageId: 'industry-statistics',
    description: "DaysFilter = '7' | '30' | 'all' (기본 '30')",
    location: 'components/statistics/statistics-page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: PERIOD_MODES,
    masking: 'server',
  },
  'statistics.company-modal': {
    label: '종목 상세 모달',
    pageId: 'industry-statistics',
    description: 'CompanyDetail. 내부 블록은 stock.* 규칙 상속(모달 우회 방지)',
    location: 'components/company-detail.tsx → components/stock/stock-detail-sections.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'server',
  },

  // ══════════════════════════════════════════════════════════════════
  //  F. 점수 랭킹 `/rankings` + `/[industryId]/rankings` — 13
  //     두 라우트가 같은 RankingsPage 를 공유하므로 featureId 는 하나다.
  // ══════════════════════════════════════════════════════════════════

  'rankings.top-picks': {
    label: '섹터킹 픽 TOP 5',
    pageId: 'rankings',
    description: '성향 가중 종합 상위 5 (topPicksByProfile)',
    location: 'components/rankings/top-picks.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'rankings.pick-profile': {
    label: '투자 성향 토글',
    pageId: 'rankings',
    description: '단기/균형/장기 가중치 전환. 클라 계산이라 재요청 없음',
    location: 'components/rankings/pick-profile-toggle.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'hidden',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'rankings.horizon-toggle': {
    label: '단기·장기 축 전환',
    pageId: 'rankings',
    description: '?sort=short URL 동기화',
    location: 'components/rankings/score-sort-toggle.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'rankings.table': {
    label: '랭킹 표 본문',
    pageId: 'rankings',
    description: '최대 100행(데스크탑 표/모바일 카드). SEO fallback 은 상위 20행',
    location: 'components/rankings/ranking-table.tsx + components/rankings/ranking-card-list.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
    seoIndexed: true,
  },
  'rankings.short-score': {
    label: '단기 점수 컬럼',
    pageId: 'rankings',
    description: '0~100 + 막대. SEO fallback 표에도 나온다',
    location: 'components/rankings/ranking-table.tsx BASE_COLUMNS short',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
    seoIndexed: true,
  },
  'rankings.long-score': {
    label: '장기 점수 컬럼',
    pageId: 'rankings',
    description: '0~100 + 막대. SEO fallback 표의 정렬 기준',
    location: 'components/rankings/ranking-table.tsx BASE_COLUMNS long',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
    seoIndexed: true,
  },
  'rankings.dcf-score': {
    label: '가치 점수(DCF) 컬럼',
    pageId: 'rankings',
    description: 'lib/dcf.ts 산출 0~100',
    location: 'components/rankings/ranking-table.tsx BASE_COLUMNS dcf',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'rankings.dcf-upside': {
    label: '적정가 대비 컬럼',
    pageId: 'rankings',
    description: 'DCF 상승예측 %',
    location: 'components/rankings/ranking-table.tsx BASE_COLUMNS dcfUpside',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'rankings.analyst-block': {
    label: '투자의견·목표주가·상승여력',
    pageId: 'rankings',
    description:
      '3컬럼 묶음. 주의 — 투자의견은 `/rankings` SEO fallback 표에도 노출되므로 게이트 시 그 표도 함께 줄여야 cloaking 이 아니다',
    location: 'components/rankings/ranking-table.tsx BASE_COLUMNS rec/target/upside',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
    seoIndexed: true,
  },
  'rankings.profitability': {
    label: 'ROE·영업이익률 컬럼',
    pageId: 'rankings',
    description: '수익성 2컬럼',
    location: 'components/rankings/ranking-table.tsx BASE_COLUMNS roe/margin',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
  },
  'rankings.advanced-columns': {
    label: '추가 지표 컬럼군',
    pageId: 'rankings',
    description: 'PER·PEG·이익성장·베타·부채비율·시가총액 (토글)',
    location: 'components/rankings/ranking-table.tsx ADVANCED_COLUMNS + rankings-page.tsx 토글',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'hidden',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'rankings.methodology-note': {
    label: '점수 산출 안내',
    pageId: 'rankings',
    description: '접이식 설명 + /methodology 링크',
    location: 'components/rankings/rankings-page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'rankings.company-modal': {
    label: '종목 상세 모달',
    pageId: 'rankings',
    description: 'CompanyDetail. 내부 블록은 stock.* 규칙 상속(모달 우회 방지)',
    location: 'components/rankings/rankings-page.tsx → components/company-detail.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'server',
  },

  // ══════════════════════════════════════════════════════════════════
  //  G. 시장 규모 `/market-size` — 8
  // ══════════════════════════════════════════════════════════════════

  'market-size.industry-map': {
    label: '산업·섹터 시총 지도',
    pageId: 'market-size',
    description: 'squarify 트리맵(산업 9개 그룹 안에 섹터 타일)',
    location: 'components/market-size/market-size-industry-map.tsx + lib/treemap.ts',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: LIST_MODES,
    masking: 'display',
  },
  'market-size.sector-drilldown': {
    label: '섹터 → 종목 타일',
    pageId: 'market-size',
    description: '섹터 클릭 시 종목 시총 지도 + 14일 등락 색',
    location: 'components/market-size/market-size-page.tsx (drillSector + useSectorCompanies)',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'market-size.growth-bars': {
    label: '매출 성장률 랭킹 막대',
    pageId: 'market-size',
    description: '시총가중 매출 성장률 상위 12 (현재 limit=12)',
    location: 'components/market-size/market-size-metric-bars.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'market-size.upside-bars': {
    label: '목표주가 상승여력 막대',
    pageId: 'market-size',
    description: '시총가중 상승여력 상위 12',
    location: 'components/market-size/market-size-metric-bars.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'market-size.bubble-view': {
    label: '성장 전망 버블 뷰',
    pageId: 'market-size',
    description: 'PC 전용 막대↔버블 토글. 막대와 동일 데이터의 다른 표현',
    location: 'components/market-size/market-size-bubble-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'hidden',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'market-size.category-drill': {
    label: '카테고리 → 섹터 드릴',
    pageId: 'market-size',
    description: '막대/버블에서 카테고리 선택',
    location: 'components/market-size/market-size-page.tsx (selectedCategoryId)',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'market-size.industry-select': {
    label: '산업 선택 셀렉트',
    pageId: 'market-size',
    description: '전체 산업/개별 산업',
    location: 'components/market-size/market-size-page.tsx (industry-select)',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'market-size.explainer': {
    label: '설명 패널',
    pageId: 'market-size',
    description: '지표 정의·한계 접이식',
    location: 'components/market-size/market-size-explainer.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },

  // ══════════════════════════════════════════════════════════════════
  //  H. 애널리스트 성적표 `/analysts`, `/analysts/[id]` — 13
  // ══════════════════════════════════════════════════════════════════

  'analysts.leaderboard': {
    label: '애널리스트 랭킹',
    pageId: 'analysts',
    description: '순위·예측력 점수·적중률·커버종목·리포트 수',
    location: 'components/analysts/analysts-page.tsx (AnalystTab)',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'analysts.hit-rate': {
    label: '적중률·표본 컬럼',
    pageId: 'analysts',
    description: '방향 적중률 % + 채점 건수. 상위 K개를 가리는 역방향 partial(blurTopK) 대상',
    location: 'components/analysts/analysts-page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'analysts.score': {
    label: '예측력 점수',
    pageId: 'analysts',
    description: '적중률 × 표본 반영 0~100',
    location: 'components/analysts/analysts-page.tsx + components/analysts/ui.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'analysts.rank-mode': {
    label: '순위 기준 전환',
    pageId: 'analysts',
    description: '예측력 점수 / 리포트 최다',
    location: 'components/analysts/analysts-page.tsx (RANKS)',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'analysts.stock-list': {
    label: '종목 탭 리스트',
    pageId: 'analysts',
    description: '종목별 커버 애널 수·리포트 수',
    location: 'components/analysts/analysts-page.tsx (StockTab)',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: LIST_MODES,
    masking: 'display',
  },
  'analysts.stock-consensus': {
    label: '컨센서스·현재가·상승여력',
    pageId: 'analysts',
    description: '종목행 3컬럼',
    location: 'components/analysts/analysts-page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'analysts.stock-sort': {
    label: '종목 정렬',
    pageId: 'analysts',
    description: '커버 애널 수/리포트 수/상승여력/종목명',
    location: 'components/analysts/analysts-page.tsx (SORTS)',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'analysts.stock-target-chart': {
    label: '종목별 목표가 차트',
    pageId: 'analysts',
    description: '애널별 목표가 계단선 vs 실제 주가 (현재 TOP_N=5)',
    location: 'components/analysts/stock-detail-body.tsx + components/analysts/target-lines-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'blur',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'analysts.stock-overlay': {
    label: '겹쳐보기(종목 탭)',
    pageId: 'analysts',
    description: '애널 칩 클릭으로 선 추가. 데이터는 이미 차트 API 로 내려온 것',
    location: 'components/analysts/stock-detail-body.tsx (selected state)',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'hidden',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'analysts.detail-page': {
    label: '애널 상세 라우트',
    pageId: 'analyst-detail',
    description: '/analysts/[id] 전용 페이지 (/api/analysts/[id] 응답 전체가 마스킹 대상)',
    location: 'app/analysts/[id]/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'hidden',
    supportedGateModes: CONTROL_MODES,
    masking: 'server',
  },
  'analysts.detail-target-chart': {
    label: '애널 상세 목표가 차트',
    pageId: 'analyst-detail',
    description: '이 애널의 종목별 목표가 vs 주가',
    location: 'components/analysts/analyst-detail-body.tsx (TickerPanel + TargetLinesChart)',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'analysts.detail-overlay': {
    label: '겹쳐보기(애널 상세)',
    pageId: 'analyst-detail',
    description: '다른 애널 목표가 선 추가',
    location: 'components/analysts/analyst-detail-body.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'hidden',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'analysts.report-verdicts': {
    label: '적중/빗나감 판정 목록',
    pageId: 'analyst-detail',
    description: '리포트별 hit/miss/unscorable 판정',
    location: 'components/analysts/analyst-detail-body.tsx (STATUS_META)',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'blur',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },

  // ══════════════════════════════════════════════════════════════════
  //  I. 종목 상세 `/stock/[ticker]` — 18
  //     (아래 stock.* 규칙은 CompanyDetail 모달 3곳에도 그대로 상속된다)
  // ══════════════════════════════════════════════════════════════════

  'stock.seo-facts': {
    label: '초기 HTML 핵심 수치',
    pageId: 'stock',
    description:
      '시총·현재가·등락·52주·섹터 — 크롤러가 읽는 본문 그 자체. 카탈로그 §5 잠금 봉인 대상',
    location: 'components/seo/stock-seo-facts.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'stock.insight-hero': {
    label: '요약 히어로',
    pageId: 'stock',
    description: '현재가·시총·52주 위치·패권 점수·상승여력 (상승여력만 부분 마스킹 대상)',
    location: 'components/stock/insights/insight-hero.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'stock.price-banner': {
    label: '시세 배너',
    pageId: 'stock',
    description:
      '현재가·누적 변동·시총·외부 링크. 무료 사이트 어디서나 얻는 값이라 카탈로그 §5 잠금 봉인 대상',
    location: 'components/stock/stock-price-banner.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'stock.short-long-scores': {
    label: '단기·장기 점수',
    pageId: 'stock',
    description: '랭킹과 동일 SoT 두 점수 + 근거 팝오버',
    location: 'components/stock/insights/short-long-scores.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
  },
  'stock.hegemony-score': {
    label: '패권 점수 분석',
    pageId: 'stock',
    description: '총점 + 규모/성장성/수익성/시장평가 4분해',
    location: 'components/stock/stock-score-analysis.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'stock.dcf': {
    label: '가치 점수(DCF)',
    pageId: 'stock',
    description: '0~100 + 상승예측% + 적정가 + 할인율 + 연도별 FCF 표',
    location: 'components/stock/stock-dcf-section.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'stock.signal-summary': {
    label: '종합 시그널',
    pageId: 'stock',
    description: '룰 기반 강점/주의 불릿',
    location: 'components/stock/insights/signal-summary.tsx + lib/stock-signals.ts',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'stock.score-trend': {
    label: '점수 추이 차트',
    pageId: 'stock',
    description: 'smoothed_score + 4구성요소 토글 (최근 N일)',
    location: 'components/stock/insights/score-trend-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'stock.sector-position': {
    label: '섹터 내 포지션',
    pageId: 'stock',
    description: 'peer 미니 테이블 + 시총 점유율 바',
    location: 'components/stock/insights/sector-position.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'stock.pe-band': {
    label: 'PER 밴드',
    pageId: 'stock',
    description: '자기 이력 25~75 백분위 + 현재 위치',
    location: 'components/stock/insights/pe-band-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'stock.price-chart': {
    label: '가격 차트',
    pageId: 'stock',
    description: '30/74/전체 기간 토글 (장기 구간이 유료 가치)',
    location: 'components/stock/insights/price-chart-section.tsx + components/price-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'stock.dominance': {
    label: '패권 포지션',
    pageId: 'stock',
    description: 'N개 섹터 중 M개 1위 + 섹터 뱃지',
    location: 'components/stock/stock-detail-page.tsx (DominanceCard) + components/stock/stock-hegemony-badges.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
  },
  'stock.financials': {
    label: '재무 지표',
    pageId: 'stock',
    description: 'ROE·영업이익률·부채비율·베타',
    location: 'components/stock/insights/financial-analyst.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
  },
  'stock.analyst-consensus': {
    label: '애널리스트 컨센서스',
    pageId: 'stock',
    description: '투자의견·목표주가·애널 수',
    location: 'components/stock/insights/financial-analyst.tsx (애널리스트 블록)',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'stock.recommendation-trend': {
    label: '의견 분포 추이',
    pageId: 'stock',
    description: '기간별 5등급 인원수 100% 누적 막대',
    location: 'components/stock/insights/recommendation-trend.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'stock.valuation-compare': {
    label: '밸류에이션 상대비교',
    pageId: 'stock',
    description: 'PER/PEG/ROE vs 섹터 중앙값 + 백분위',
    location: 'components/stock/insights/valuation-compare.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'basic',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'stock.watch-toggle': {
    label: '워치리스트 추가',
    pageId: 'stock',
    description:
      '별 토글(쓰기 API). 현재는 비로그인에게도 버튼이 보이고 클릭 시 /login?redirect= 로 보낸다',
    location: 'components/me/watch-star-toggle.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'hidden',
    supportedGateModes: CONTROL_MODES,
    masking: 'server',
  },
  'stock.share': {
    label: '공유',
    pageId: 'stock',
    description: '링크 공유 버튼 (값이 없는 UI 컨트롤)',
    location: 'components/share-button.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },

  // ══════════════════════════════════════════════════════════════════
  //  J-1. 섹터 허브 `/sectors` — 1 (전량 잠금 봉인)
  // ══════════════════════════════════════════════════════════════════

  'sectors.index': {
    label: '섹터 목록',
    pageId: 'sectors',
    description: '색인 가능한 섹터 109개 링크 목록. 홈→산업→섹터→종목 크롤 경로의 고리',
    location: 'app/sectors/page.tsx + lib/sector-server.ts (getIndexableSectors)',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },

  // ══════════════════════════════════════════════════════════════════
  //  J-2. 섹터 상세 `/sectors/[sectorId]` — 3 (전량 잠금 봉인)
  // ══════════════════════════════════════════════════════════════════

  'sector.company-table': {
    label: '섹터 종목 표',
    pageId: 'sector-detail',
    description: '종목·티커·상장·시총·현재가·전일대비. SSG 109개의 본문',
    location: 'app/sectors/[sectorId]/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'sector.period-change': {
    label: '기간 변화율',
    pageId: 'sector-detail',
    description: '양쪽 날짜 모두 존재하는 종목만 분모에 넣은 기간 변화율',
    location: 'app/sectors/[sectorId]/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'sector.related': {
    label: '관련 섹터',
    pageId: 'sector-detail',
    description: '동일 카테고리 섹터 링크',
    location: 'app/sectors/[sectorId]/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },

  // ══════════════════════════════════════════════════════════════════
  //  J-3. 세계 지수 `/indices` — 2
  // ══════════════════════════════════════════════════════════════════

  'indices.table': {
    label: '세계 지수 표',
    pageId: 'indices',
    description: '국가·지수·현재·1d·1w·1m·1y·52주 위치 (1y·52주 컬럼만 게이트 후보)',
    location: 'components/indices/indices-page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'indices.comparison-chart': {
    label: '지수 비교 차트',
    pageId: 'indices',
    description: '다중 지수 정규화 비교 (/api/indices/history 응답 전체가 마스킹 대상)',
    location: 'components/indices/indices-comparison-chart.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },

  // ══════════════════════════════════════════════════════════════════
  //  J-4. 전역 셸 — 6 (값이 없는 UI 컨트롤)
  // ══════════════════════════════════════════════════════════════════

  'shell.global-search': {
    label: '전역 검색',
    pageId: 'shell',
    description: '종목·섹터 검색 오버레이 (/api/search)',
    location: 'components/global-search.tsx + search-trigger.tsx + search-provider.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'shell.nav': {
    label: '주요 메뉴',
    pageId: 'shell',
    description: '소개/뉴스/시장 규모/섹터킹 픽/애널리스트/세계 지수',
    location: 'components/layout/global-top-bar.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'shell.theme-toggle': {
    label: '다크모드 토글',
    pageId: 'shell',
    description: '라이트/다크 전환',
    location: 'components/theme-toggle.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'shell.currency-toggle': {
    label: '통화 토글',
    pageId: 'shell',
    description: '₩/$ 표시 전환',
    location: 'components/currency-toggle.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'shell.auth-button': {
    label: '로그인/사용자 메뉴',
    pageId: 'shell',
    description: '로그인 버튼 또는 사용자 드롭다운. 인증 경로라 잠글 수 없다',
    location: 'components/auth/auth-button-client.tsx + components/auth/user-menu.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
  },
  'shell.share': {
    label: '공유 버튼',
    pageId: 'shell',
    description: '현재 페이지 링크 공유',
    location: 'components/share-button.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },

  // ══════════════════════════════════════════════════════════════════
  //  K. 마켓 리포트 `/news`, `/news/[id]` — 12
  //     이미 게이팅이 구현된 유일한 영역. defaultPolicy 가 현행 동작이다.
  // ══════════════════════════════════════════════════════════════════

  'news.list': {
    label: '리포트 목록',
    pageId: 'news',
    description: '발행 리포트 50건 카드. 무료 공개 정책 + IndexNow 통지 대상',
    location: 'app/news/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'news.kind-filter': {
    label: '종류 필터',
    pageId: 'news',
    description: '전체/월별/데일리',
    location: 'app/news/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'news.view-toggle': {
    label: '초보/전문가 뷰 전환',
    pageId: 'news-detail',
    description: '리포트 본문 뷰 모드 전환',
    location: 'components/news/view-toggle.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'news.novice-body': {
    label: '초보자용 본문',
    pageId: 'news-detail',
    description: '요약·이벤트·주목 종목·한 줄 정리. 무료 공개 정책',
    location: 'components/news/novice-report-view.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'news.novice-korea': {
    label: '초보 뷰 한국 주식 섹션',
    pageId: 'news-detail',
    description:
      '"한국 주식은 뭘 봐야 해?" — 현행: 비로그인이면 LockedSection variant=blur. 다만 원문이 DOM 에 남아 우회 가능하므로 서버 마스킹으로 옮겨야 한다',
    location: 'components/news/novice-report-view.tsx (LockedSection variant=blur)',
    defaultPolicy: { minTier: 'free', gateMode: 'blur' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'news.expert-body': {
    label: '전문가용 A~D',
    pageId: 'news-detail',
    description: '30초 브리핑·헤드라인·테마 맵·액션',
    location: 'components/news/expert-report-view.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
    seoIndexed: true,
  },
  'news.expert-locked': {
    label: '전문가용 E~H',
    pageId: 'news-detail',
    description:
      '시나리오·한 줄 결론·자금흐름 맵·한국 주식 — 현행: 비로그인이면 LockedSection variant=fade(280px). fade 는 상단 일부만 보이므로 teaser 로 표기한다. 원문이 DOM 에 남아 우회 가능',
    location: 'components/news/expert-report-view.tsx (LockedSection variant=fade)',
    defaultPolicy: { minTier: 'free', gateMode: 'teaser' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'teaser',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'news.monthly-korea-coverage': {
    label: '월간 한국 커버리지',
    pageId: 'news-detail',
    description:
      '종목·의견·코멘트 표 — 현행: 비로그인이면 **상위 3건이 블러**되고 4번째부터 공개된다(코드 실측: slice(0,3) 블러 + slice(3) 노출). 카탈로그가 "상위 3건만 노출"이라 적은 것은 반대로 읽은 것이다. 역방향 partial = blurTopK 3',
    location: 'components/news/report/monthly-report-view.tsx',
    defaultPolicy: { minTier: 'free', gateMode: 'partial', params: { blurTopK: 3 } },
    recommendedMinTier: 'free',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'news.monthly-outlook': {
    label: '월간 전망',
    pageId: 'news-detail',
    description:
      '다음 달 전망 — 현행: 요약·핵심 총정리는 공개하고 상세만 LockedSection variant=fade(180px). 요약을 남기므로 teaser 로 표기한다',
    location: 'components/news/report/monthly-report-view.tsx (LockedSection variant=fade)',
    defaultPolicy: { minTier: 'free', gateMode: 'teaser' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'blur',
    supportedGateModes: BLOCK_MODES,
    masking: 'server',
  },
  'news.monthly-body': {
    label: '월간 본문 01~04·06',
    pageId: 'news-detail',
    description: '총평·자금흐름·로테이션·주요 등락·전망 헤더',
    location: 'components/news/report/monthly-report-view.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: BLOCK_MODES,
    masking: 'display',
    seoIndexed: true,
  },
  'news.toc': {
    label: '목차',
    pageId: 'news-detail',
    description: '스티키 TOC',
    location: 'components/news/sticky-toc.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'news.subscribe-cta': {
    label: '구독 CTA',
    pageId: 'news-detail',
    description: '이메일 구독 유도',
    location: 'components/news/news-subscribe-cta.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },

  // ══════════════════════════════════════════════════════════════════
  //  L. 내 페이지 `/me/**` — 9
  //     /me 5개 라우트는 이미 requireUser 가 지킨다 → defaultPolicy free.
  // ══════════════════════════════════════════════════════════════════

  'me.home': {
    label: '내 페이지 홈',
    pageId: 'me-home',
    description: '워치리스트 카드 + 바로가기 + 최근 본 종목. requireUser("/me") 적용 중',
    location: 'app/me/page.tsx',
    defaultPolicy: { minTier: 'free', gateMode: 'hidden' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'hidden',
    supportedGateModes: CONTROL_MODES,
    masking: 'server',
  },
  'me.watchlist': {
    label: '워치리스트',
    pageId: 'me-watchlist',
    description: '종목/섹터 즐겨찾기 관리. requireUser("/me/watchlist") 적용 중. 무료 상한은 미정',
    location: 'app/me/watchlist/watchlist-manager.tsx + components/me/my-watchlist-card.tsx',
    defaultPolicy: { minTier: 'free', gateMode: 'hidden' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'me.notes': {
    label: '내 메모',
    pageId: 'me-notes',
    description: '종목별 메모 CRUD (/api/me/notes). requireUser("/me/notes") 적용 중',
    location: 'components/me/note-list.tsx + components/me/note-editor.tsx',
    defaultPolicy: { minTier: 'free', gateMode: 'hidden' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'partial',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'me.recently-viewed': {
    label: '최근 본 종목',
    pageId: 'me-home',
    description: '최근 조회 이력 (/api/me/recently-viewed). /me 홈에 마운트',
    location: 'components/me/recently-viewed-row.tsx',
    defaultPolicy: { minTier: 'free', gateMode: 'hidden' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'open',
    supportedGateModes: LIST_MODES,
    masking: 'server',
  },
  'me.email-subscription': {
    label: '이메일 구독 설정',
    pageId: 'me-settings',
    description: '일별 메일 on/off. requireUser("/me/settings") 적용 중',
    location: 'components/me/email-subscription-section.tsx + email-subscription-toggle.tsx',
    defaultPolicy: { minTier: 'free', gateMode: 'hidden' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'server',
  },
  'me.settings-profile': {
    label: '프로필 정보',
    pageId: 'me-settings',
    description: '이름·이메일·역할 표시. requireUser("/me/settings") 적용 중',
    location: 'app/me/settings/page.tsx',
    defaultPolicy: { minTier: 'free', gateMode: 'hidden' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'server',
  },
  'me.onboarding': {
    label: '온보딩 관심 선택',
    pageId: 'me-onboarding',
    description: '관심 산업/섹터 픽. requireUser("/me/onboarding") 적용 중',
    location: 'components/me/onboarding-picker-step.tsx',
    defaultPolicy: { minTier: 'free', gateMode: 'hidden' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'server',
  },
  'me.home-slot': {
    label: '홈 개인화 슬롯',
    pageId: 'home',
    description:
      '로그인 사용자 홈 위젯(비로그인이면 로그인 유도 카드). 실측 결과 현재 어떤 페이지에도 마운트되어 있지 않다 — 홈 마운트를 전제로 등록',
    location: 'components/me/my-home-slot.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'free',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'server',
  },
  'me.login-prompt': {
    label: '로그인 유도 카드',
    pageId: 'home',
    description:
      '비로그인용 가치 제안. my-home-slot 안에서만 쓰이므로 현재 화면에 나타나지 않는다(미마운트)',
    location: 'components/me/login-value-prompt-card.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },

  // ══════════════════════════════════════════════════════════════════
  //  M. 문서 · 법적 · 인증 — 14 (design-system 제외 전부 잠금 봉인)
  // ══════════════════════════════════════════════════════════════════

  'guide.hub': {
    label: '이용 안내 허브',
    pageId: 'guide',
    description: 'ServiceIntro·NumberGlossary·ScreenGuide·ValuationMetricGuide·HonestLimits',
    location: 'app/guide/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'guide.money-flow': {
    label: '자금 흐름 읽는 법',
    pageId: 'guide-money-flow',
    description: '비브랜드 유입 가이드 (MFI 표준 대비 차이 명시)',
    location: 'app/guide/how-to-read-money-flow/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'guide.mcap-vs-netbuy': {
    label: '시총 변화 vs 순매수',
    pageId: 'guide-mcap-vs-netbuy',
    description: '자금 흐름 = 시총 변화액이라는 한계를 설명하는 문서',
    location: 'app/guide/market-cap-change-vs-net-buying/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'guide.sector-rotation': {
    label: '섹터 로테이션',
    pageId: 'guide-sector-rotation',
    description: '비브랜드 유입 가이드',
    location: 'app/guide/sector-rotation/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'methodology.doc': {
    label: '방법론 8개 절',
    pageId: 'methodology',
    description: '숫자의 산출식. 유료화 근거를 설명하는 신뢰 문서라 잠글 수 없다',
    location: 'app/methodology/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'data-sources.doc': {
    label: '데이터 출처',
    pageId: 'data-sources',
    description: '수집 소스·주기·한계. E-E-A-T 신호',
    location: 'app/data-sources/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'editorial-policy.doc': {
    label: '편집 정책',
    pageId: 'editorial-policy',
    description: '리포트 작성·정정 정책',
    location: 'app/editorial-policy/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'about.doc': {
    label: '서비스 소개 + 기여자',
    pageId: 'about',
    description: '비브랜드 유입의 착지점이자 전환 퍼널 입구',
    location: 'app/about/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'contact.form': {
    label: '문의·제보 폼',
    pageId: 'contact',
    description: '결제·환불·오류 제보 창구 (/api/contact). 막으면 불만 처리 경로가 사라진다',
    location: 'components/contact/contact-form.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
  },
  'terms.doc': {
    label: '이용약관',
    pageId: 'terms',
    description: '계약 성립 전에 읽을 수 있어야 한다. 결제 화면이 링크로 참조',
    location: 'app/terms/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'privacy.doc': {
    label: '개인정보 처리방침',
    pageId: 'privacy',
    description: '동의 절차의 전제 문서. 로그인 뒤에 둘 수 없다',
    location: 'app/privacy/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
    seoIndexed: true,
  },
  'design-system.doc': {
    label: '디자인 시스템',
    pageId: 'design-system',
    description:
      '내부 개발용 참조 페이지. 카탈로그는 admin 권장이나 게이팅 대신 noindex 로 충분하다는 판단도 열려 있다(결정 필요)',
    location: 'app/design-system/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: CONTROL_MODES,
    masking: 'display',
  },
  'login.page': {
    label: '로그인',
    pageId: 'login',
    description: '로그인 페이지를 로그인 뒤에 둘 수 없다',
    location: 'app/login/page.tsx + components/auth/google-sign-in-button.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
  },
  'email.unsubscribed': {
    label: '구독 해지 완료',
    pageId: 'email-unsubscribed',
    description: '수신거부는 이메일 수신자가 로그인 없이 처리할 수 있어야 한다(법적 요구)',
    location: 'app/email/unsubscribed/page.tsx',
    defaultPolicy: { minTier: 'anon', gateMode: 'open' },
    recommendedMinTier: 'anon',
    recommendedGateMode: 'open',
    supportedGateModes: SEALED_OPEN,
    masking: 'display',
  },

  // ══════════════════════════════════════════════════════════════════
  //  N. 관리자 `/admin/**` — 15
  //     app/admin/layout.tsx 의 requireAdmin 이 이미 서버 게이트다.
  //     supportedGateModes 를 ['hidden'] 으로 고정해 운영자가 손대지 못하게 한다.
  // ══════════════════════════════════════════════════════════════════

  'admin.dashboard': {
    label: '관리자 대시보드',
    pageId: 'admin-home',
    description: 'requireAdmin("/admin") 적용 중',
    location: 'app/admin/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.news-list': {
    label: '리포트 목록',
    pageId: 'admin-news',
    description: 'requireAdmin 적용 중',
    location: 'app/admin/news/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.news-create': {
    label: '리포트 작성',
    pageId: 'admin-news-new',
    description: 'requireAdmin 적용 중',
    location: 'app/admin/news/new/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.news-edit': {
    label: '리포트 수정',
    pageId: 'admin-news-edit',
    description: 'requireAdmin 적용 중. 발행 시 IndexNow 통지 지점',
    location: 'app/admin/news/[id]/edit/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.news-email-preview': {
    label: '발송 메일 미리보기',
    pageId: 'admin-news-preview-email',
    description: 'requireAdmin 적용 중',
    location: 'app/admin/news/[id]/preview-email/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.econ-calendar-list': {
    label: '경제 캘린더 관리',
    pageId: 'admin-econ-calendar',
    description: 'requireAdmin 적용 중',
    location: 'app/admin/economic-calendar/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.econ-calendar-create': {
    label: '이벤트 등록',
    pageId: 'admin-econ-calendar-new',
    description: 'requireAdmin 적용 중',
    location: 'app/admin/economic-calendar/new/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.econ-calendar-edit': {
    label: '이벤트 수정',
    pageId: 'admin-econ-calendar-edit',
    description: 'requireAdmin 적용 중',
    location: 'app/admin/economic-calendar/[id]/edit/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.contributors-list': {
    label: '기여자 관리',
    pageId: 'admin-contributors',
    description: 'requireAdmin 적용 중',
    location: 'app/admin/contributors/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.contributors-create': {
    label: '기여자 등록',
    pageId: 'admin-contributors-new',
    description: 'requireAdmin 적용 중',
    location: 'app/admin/contributors/new/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.contributors-edit': {
    label: '기여자 수정',
    pageId: 'admin-contributors-edit',
    description: 'requireAdmin 적용 중',
    location: 'app/admin/contributors/[id]/edit/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.contact-list': {
    label: '문의 관리',
    pageId: 'admin-contact',
    description: 'requireAdmin 적용 중',
    location: 'app/admin/contact/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.contact-detail': {
    label: '문의 상세',
    pageId: 'admin-contact-detail',
    description: 'requireAdmin 적용 중',
    location: 'app/admin/contact/[id]/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.users': {
    label: '사용자 관리',
    pageId: 'admin-users',
    description: 'requireAdmin 적용 중. 등급 부여 화면이 붙을 자리',
    location: 'app/admin/users/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
  'admin.email-log': {
    label: '이메일 발송 로그',
    pageId: 'admin-email-log',
    description: 'requireAdmin 적용 중',
    location: 'app/admin/email-log/page.tsx',
    defaultPolicy: { minTier: 'admin', gateMode: 'hidden' },
    recommendedMinTier: 'admin',
    recommendedGateMode: 'hidden',
    supportedGateModes: ADMIN_FIXED,
    masking: 'server',
  },
}

export type FeatureId = keyof typeof FEATURES

/** 전체 featureId. 정렬은 페이지 순서 → 등록 순서. */
export const FEATURE_IDS: string[] = Object.keys(FEATURES)

export function getFeature(featureId: string): FeatureDef | undefined {
  return FEATURES[featureId]
}

export function getPage(pageId: string): PageDef | undefined {
  return PAGES.find((p) => p.id === pageId)
}

/** 한 페이지에 속한 기능들. 어드민 우측 표가 이 결과를 그린다. */
export function featuresByPage(pageId: string): Array<[string, FeatureDef]> {
  return Object.entries(FEATURES).filter(([, def]) => def.pageId === pageId)
}

/**
 * 게이트가 실제로 배선된 기능 (`FeatureDef.wired`).
 *
 * **현재 0건이다.** 이 시스템은 정책 저장·판정·미리보기까지를 담당하고,
 * 개별 화면에 `FeatureGate` 를 붙이고 API 에 서버 마스킹을 넣는 일은 기능마다
 * 별도 커밋으로 진행한다. 콘솔이 이 목록을 근거로 "설정해도 화면은 아직 안
 * 바뀝니다" 를 표시한다.
 */
export const WIRED_FEATURE_IDS: string[] = Object.entries(FEATURES)
  .filter(([, def]) => def.wired === true)
  .map(([id]) => id)
